### ISSUE TITLE
VirtualBox Guest additions check sum not matching

### ISSUE THREAD

**Issue by ArchaicLord** [heizo/packer-ubuntu-18.04#1]
I haven't used packer before. Was refered to this as a solution to building a VM development machine. 

I cloned the repo, installed packer and ran the commad specified on the README.md

I got the following error. 

` virtualbox-iso: Downloading or copying: http://cdimage.ubuntu.com/ubuntu/releases/bionic/release/ubuntu-18.04-server-amd64.iso
    virtualbox-iso: Error downloading: checksums didn't match expected: 73ae6579ef7c51d944a0be5c4c48f748bfd689df
==> virtualbox-iso: ISO download failed.
Build 'virtualbox-iso' errored: ISO download failed.`

I presume you are using a version you already downloaded. Could you let me know what version so I can match it please. 

is it possible to update this so its negated for others in the future?

**Comment by alanwj** [comment]
I created pull request #2 which I believe addresses this by updating to 18.04.1 and updating the checksum.

**Comment by heizo** [comment]
Thanks! I'm sorry I didn't notice immediately.
